FROM node:18-alpine

WORKDIR /usr/src/app

COPY backend/package*.json ./
RUN npm ci --production

COPY backend/ ./

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080
CMD ["node", "server.js"]
