FROM node:16-alpine AS build
WORKDIR /usr/src/app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build

FROM nginx:stable-alpine

RUN rm -f /etc/nginx/conf.d/default.conf || true

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/app/dist/angular-15-crud/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

